name: Security Scans

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitleaks:
    name: Ejecutar Gitleaks + Trivy Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          version: "latest"

      - name: Ejecutar an√°lisis con Gitleaks
        run: |
          gitleaks detect \
            --source . \
            --report-format json \
            --report-path gitleaks-report.json \
            --config .gitleaks.toml \
            --no-color

      # Build de imagen Docker
      - name: Construir imagen Docker
        run: |
          docker build -t mi-api:latest .
          
      - name: Esperar antes de install Trivy
        run: sleep 10

      - name: Escanear imagen con Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          scan-ref: mi-api:latest
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'  # Falla si detecta vulnerabilidades
          output: trivy-report.txt

      - name: Subir reportes como artefactos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            gitleaks-report.json
            trivy-report.txt

